language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # version tags


install:
  - pip install mkdocs pyyaml pytest click

script:
  - pytest

deploy:
  provider: pypi
  distributions: sdist
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
    python: 3.7

notifications:
  email:
    on_success: never
